name: Release crate

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login
        run: cargo login ${{ secrets.CARGO_LOGIN_TOKEN }}
      - name: Publish crate
        run: cargo publish

